"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.base64UserData = exports.userData = void 0;
var vitest_1 = require("vitest");
var metadata_1 = require("./metadata");
/**
 * This is an example cloud-init config
 */
exports.userData = "#cloud-config\npackage_update: true\npackage_upgrade: true\npackages:\n- nginx\n- mysql-server\n";
/**
 * This is the base64 encoded version of `userData`.
 * It was generated by base64 --break=0 --input=[file name here]
 */
exports.base64UserData = 'I2Nsb3VkLWNvbmZpZwpwYWNrYWdlX3VwZGF0ZTogdHJ1ZQpwYWNrYWdlX3VwZ3JhZGU6IHRydWUKcGFja2FnZXM6Ci0gbmdpbngKLSBteXNxbC1zZXJ2ZXIK';
(0, vitest_1.describe)('utoa', function () {
    (0, vitest_1.it)('should produce base64 encoded user data', function () {
        (0, vitest_1.expect)((0, metadata_1.utoa)(exports.userData)).toBe(exports.base64UserData);
    });
});
